name = "Fabulously Optimized"
author = "robotkoer"
version = "3.5.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c59fd8185c30d43a3fc228db06b0a4fe540de4f8759c556a0bc9f897b749d81"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
