name = "Fabulously Optimized"
author = "robotkoer"
version = "3.5.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c23e6eeb9e8c2a73c6a905f34ff7b87a978526cc9528f477fc9e10f61ff4ce2"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
