name = "Fabulously Optimized"
author = "robotkoer"
version = "3.5.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d759c1daa40a0e64ab093fbe8c9cbfdde2dc06847b62631493f2e4650f7a7aab"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
