name = "Fabulously Optimized"
author = "robotkoer"
version = "3.5.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b163ba9666daa19675ba981438cbb8e82d6c0bca33e171fe8253643f1fb3f62"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
